### ISSUE TITLE
Script txt

### ISSUE THREAD

**Issue by chuliu-hash** [imKota/SystemCTools#1]
My script files within the data.fpk appear like this, starting with ACT_*. txt. Is it possible to extract such text without any additional content and also re-inject it back?
[](url)
[ACT_A.txt](https://github.com/imKota/SystemCTools/files/12455918/ACT_A.txt)

**Comment by imKota** [comment]
@17858911252 send me your data.fpk

**Comment by imKota** [comment]
@chuliu-hash [data.zip](https://github.com/imKota/SystemCTools/files/12470346/data.zip)

1. Run `1.Script export.bat` for get text from scripts.
2. Go to **data** folder and edit ACT_*.csv
3. Run `2.Script import.bat` for insert text and rebuild scripts.
4. Run `5.fpk repack.bat` for repack folder **data**
5. Copy `data_new.fpk` to game foilder and rename to `data.fpk`

**Comment by chuliu-hash** [comment]
> @chuliu-hash [data.zip](https://github.com/imKota/SystemCTools/files/12470346/data.zip)
> 
>     1. Run `1.Script export.bat` for get text from scripts.
> 
>     2. Go to **data** folder and edit ACT_*.csv
> 
>     3. Run `2.Script import.bat` for insert text and rebuild scripts.
> 
>     4. Run `5.fpk repack.bat` for repack folder **data**
> 
>     5. Copy `data_new.fpk` to game foilder and rename to `data.fpk`

I understand.Thanks

**Comment by chuliu-hash** [comment]
> @chuliu-hash [data.zip](https://github.com/imKota/SystemCTools/files/12470346/data.zip)
> 
>     1. Run `1.Script export.bat` for get text from scripts.
> 
>     2. Go to **data** folder and edit ACT_*.csv
> 
>     3. Run `2.Script import.bat` for insert text and rebuild scripts.
> 
>     4. Run `5.fpk repack.bat` for repack folder **data**
> 
>     5. Copy `data_new.fpk` to game foilder and rename to `data.fpk`


Why is it that when I unpack data.fpk and then use the Script export.bat to extract, it shows that several non-existent *.spt files are missing? 
I have compared the *.spt files in the data folder you provided with the ones I unpacked, and they are identical.

After repacking the fpk with your provided data folder,I've noticed that the in-game text is displayed in the wrong place and  English symbols for controlling character portraits and sound effects,  
but this only happens in one particular scene.The text display for scenes before and after this one is normal.

one error:
 Unhandled exception. System.IO.FileNotFoundException: Could not find file 'D:\SystemCtools\data\B220_90.spt'.
 csv (ACT_B): Unhandled exception. System.IO.FileNotFoundException: Could not find file 'D:\SystemCtools\data\B220_90.spt'.
File name: 'D:\SystemCtools\data\B220_90.spt'
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at ScriptSection..ctor(String path)
   at Program.Script.<ParseCode>g__ParseLine|9_0(String lineText, Int32 lineNo, <>c__DisplayClass9_0& )
   at Program.Script.ParseCode(String fileName)
   at Program.ConvertFile(String path)
   at Program.Main(String[] args)
   
   I could rename B0220_90.spt to avoid this error, but I think this is causing incorrect text display in the game.

**Comment by chuliu-hash** [comment]
![图片](https://github.com/imKota/SystemCTools/assets/88051699/a225e5da-12ba-4f1c-9c52-c7ba86d25a95)
I've only noticed this problem occurring in one specific scene.

**Comment by imKota** [comment]
@chuliu-hash vn mame?

**Comment by chuliu-hash** [comment]
> @chuliu-hash vn mame?
[data.zip](https://github.com/imKota/SystemCTools/files/12529922/data.zip)


This is a patch 
Display the incorrect text in ACT_G.csv from @L723 to @L801. I compared it with the original .txt file and did not find formatting errors

**Comment by imKota** [comment]
@chuliu-hash can you say me vn name?

**Comment by imKota** [comment]
@chuliu-hash try this [data.zip](https://github.com/imKota/SystemCTools/files/12536085/data.zip)

**Comment by chuliu-hash** [comment]
> @chuliu-hash try this [data.zip](https://github.com/imKota/SystemCTools/files/12536085/data.zip)
The results are the same, there is an problem with the text in this scene, but no problems have been found in other scenes at the moment.
[Png.zip](https://github.com/imKota/SystemCTools/files/12536240/Png.zip)

**Comment by imKota** [comment]
@chuliu-hash write me https://t.me/ImKota

**Comment by chuliu-hash** [comment]
> @chuliu-hash write me https://t.me/ImKota

Sorry, I can only send messages to mutual contacts at the moment

**Comment by imKota** [comment]
> > @chuliu-hash write me https://t.me/ImKota
> 
> Sorry, I can only send messages to mutual contacts at the moment

discord?

**Comment by chuliu-hash** [comment]
> > > @chuliu-hash write me https://t.me/ImKota
> > 
> > 
> > Sorry, I can only send messages to mutual contacts at the moment
> 
> discord?

Telegram.I can't send message to you

**Comment by imKota** [comment]
> > > > @chuliu-hash write me https://t.me/ImKota
> > > 
> > > 
> > > Sorry, I can only send messages to mutual contacts at the moment
> > 
> > 
> > discord?
> 
> Telegram.I can't send message to you

try again or give me your tg

**Comment by chuliu-hash** [comment]
> https://t.me/ImKota


> > > > > @chuliu-hash write me https://t.me/ImKota
> > > > 
> > > > 
> > > > Sorry, I can only send messages to mutual contacts at the moment
> > > 
> > > 
> > > discord?
> > 
> > 
> > Telegram.I can't send message to you
> 
> try again or give me your tg

https://t.me/dieddog
